### ISSUE TITLE
Allow user to specify cache directory

### ISSUE THREAD

**Issue by stevevance** [inouet/file-cache#1]
I love how simple to use your Composer-based script is. It would be useful to allow the user to set a cache location, in case the /tmp/cache directory is unavailable.

**Comment by inouet** [comment]
Hi  stevevance

To specify the cache directory, please as follows.

``` php
<?php
$options = ['cache_dir' => __DIR__. '/cache'];

$cache = new FileCache($options);
$cache->save("hoge", "foo");
```

```
$ tree ./cache
./cache
└── 31
    └── f3
        └── 31f30ddbcb1bf8446576f0e64aa4c88a9f055e3c.cache

2 directories, 1 file
```

Thanks!

**Comment by stevevance** [comment]
It works, thank you for the instructions!
